# Generated by Django 3.0.8 on 2020-12-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc', '0005_auto_20201210_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='short_url',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
