# Generated by Django 3.0.8 on 2020-12-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc', '0010_auto_20201210_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='notuserurl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField()),
                ('short_url', models.CharField(max_length=8)),
            ],
        ),
    ]
