# Generated by Django 3.0.8 on 2021-01-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wc', '0012_shorturl_url_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notuserurl',
            name='total_notuser',
            field=models.IntegerField(default=56800235584),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='total_user',
            field=models.IntegerField(default=56800235584),
        ),
    ]
